version: "3.4"

services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - APP_KEY=base64:RgMZ9uWIVVIojeYZvT00uJv7/O7K/FNGP1yHakdfwOs=
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
      - APP_ENV=production
      - APP_TRUSTED_PROXIES=*
      - APP_URL=https://people.abdallah.work

    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql